import type { LucideIcon } from '@lucide/svelte';
import {
	Accessibility, Anchor, AppWindow, Apple, Archive, ArrowLeft, ArrowLeftRight, ArrowRight,
	ArrowUp, Atom, BadgeInfo, Ban, Barcode, Battery, Bell, Binary,
	Bird, BookOpen, Bookmark, Bot, Box, Braces, Brain, BrickWall,
	Briefcase, Broom, Bug, Calendar, Camera, CaseSensitive, ChartColumn, Check,
	ChevronDown, ChevronRight, ChevronUp, Circle, CircleCheck, CircleX, Clapperboard, Clipboard, Clock,
	CloudRain, CodeXml, Coffee, Coins, Construction, Container, Cookie, Copy,
	CornerDownLeft, CreditCard, Crop, Crosshair, Database, Diamond, Disc, Dog,
	Download, Droplet, Eye, FaceSlightlySmiling, Feather, FilePen, FileText, FingerprintPattern,
	Flag, Flame, FlaskConical, Folder, Gamepad, Gem, GitCompare, Globe,
	Grid3x3, Guitar, Hash, Heart, Highlighter, Hourglass, Image, Inbox,
	Info, Key, Keyboard, Leaf, Lightbulb, Link, List, Lock,
	LockKeyhole, LockOpen, Mail, MapPin, Medal, Menu, MessageCircle, Mic,
	Microscope, Monitor, Moon, Newspaper, Package, Palette, PanelsTopLeft, PenLine,
	Pencil, Pin, Plus, Puzzle, QrCode, Rabbit, Radio, RefreshCw,
	Regex, Rewind, Rocket, RotateCcw, Ruler, Save, Scale, Scissors, Scroll,
	Search, Settings, Shield, ShipWheel, Shuffle, SlidersVertical, Smartphone, Sparkles,
	Square, SquareCheck, Star, Sun, Table, Tag, Target, Timer,
	TrainTrack, Trash2, TreeDeciduous, TrendingUp, TriangleAlert, Tv, Type, User,
	Video, WavesHorizontal, Wifi, Wind, WholeWord, Worm, Wrench, X, Zap,
} from '@lucide/svelte';

export const lucideIcons: Record<string, LucideIcon> = {
	'accessibility': Accessibility,
	'anchor': Anchor,
	'app-window': AppWindow,
	'apple': Apple,
	'archive': Archive,
	'arrow-left': ArrowLeft,
	'arrow-left-right': ArrowLeftRight,
	'arrow-right': ArrowRight,
	'arrow-up': ArrowUp,
	'atom': Atom,
	'badge-info': BadgeInfo,
	'ban': Ban,
	'barcode': Barcode,
	'battery': Battery,
	'bell': Bell,
	'binary': Binary,
	'bird': Bird,
	'book-open': BookOpen,
	'bookmark': Bookmark,
	'bot': Bot,
	'box': Box,
	'braces': Braces,
	'brain': Brain,
	'brick-wall': BrickWall,
	'briefcase': Briefcase,
	'broom': Broom,
	'bug': Bug,
	'calendar': Calendar,
	'camera': Camera,
	'case-sensitive': CaseSensitive,
	'chart-column': ChartColumn,
	'check': Check,
	'chevron-down': ChevronDown,
	'chevron-right': ChevronRight,
	'chevron-up': ChevronUp,
	'circle': Circle,
	'circle-check': CircleCheck,
	'circle-x': CircleX,
	'clapperboard': Clapperboard,
	'clipboard': Clipboard,
	'clock': Clock,
	'cloud-rain': CloudRain,
	'code-xml': CodeXml,
	'coffee': Coffee,
	'coins': Coins,
	'construction': Construction,
	'container': Container,
	'cookie': Cookie,
	'copy': Copy,
	'corner-down-left': CornerDownLeft,
	'credit-card': CreditCard,
	'crop': Crop,
	'crosshair': Crosshair,
	'database': Database,
	'diamond': Diamond,
	'disc': Disc,
	'dog': Dog,
	'download': Download,
	'droplet': Droplet,
	'eye': Eye,
	'face-slightly-smiling': FaceSlightlySmiling,
	'feather': Feather,
	'file-pen': FilePen,
	'file-text': FileText,
	'fingerprint-pattern': FingerprintPattern,
	'flag': Flag,
	'flame': Flame,
	'flask-conical': FlaskConical,
	'folder': Folder,
	'gamepad': Gamepad,
	'gem': Gem,
	'git-compare': GitCompare,
	'globe': Globe,
	'grid-3x3': Grid3x3,
	'guitar': Guitar,
	'hash': Hash,
	'heart': Heart,
	'highlighter': Highlighter,
	'hourglass': Hourglass,
	'image': Image,
	'inbox': Inbox,
	'info': Info,
	'key': Key,
	'keyboard': Keyboard,
	'leaf': Leaf,
	'lightbulb': Lightbulb,
	'link': Link,
	'list': List,
	'lock': Lock,
	'lock-keyhole': LockKeyhole,
	'lock-open': LockOpen,
	'mail': Mail,
	'map-pin': MapPin,
	'medal': Medal,
	'menu': Menu,
	'message-circle': MessageCircle,
	'mic': Mic,
	'microscope': Microscope,
	'monitor': Monitor,
	'moon': Moon,
	'newspaper': Newspaper,
	'package': Package,
	'palette': Palette,
	'panels-top-left': PanelsTopLeft,
	'pen-line': PenLine,
	'pencil': Pencil,
	'pin': Pin,
	'plus': Plus,
	'puzzle': Puzzle,
	'qr-code': QrCode,
	'rabbit': Rabbit,
	'radio': Radio,
	'refresh-cw': RefreshCw,
	'regex': Regex,
	'rewind': Rewind,
	'rocket': Rocket,
	'rotate-ccw': RotateCcw,
	'ruler': Ruler,
	'save': Save,
	'scale': Scale,
	'scissors': Scissors,
	'scroll': Scroll,
	'search': Search,
	'settings': Settings,
	'shield': Shield,
	'ship-wheel': ShipWheel,
	'shuffle': Shuffle,
	'sliders-vertical': SlidersVertical,
	'smartphone': Smartphone,
	'sparkles': Sparkles,
	'square': Square,
	'square-check': SquareCheck,
	'star': Star,
	'sun': Sun,
	'table': Table,
	'tag': Tag,
	'target': Target,
	'timer': Timer,
	'train-track': TrainTrack,
	'trash-2': Trash2,
	'tree-deciduous': TreeDeciduous,
	'trending-up': TrendingUp,
	'triangle-alert': TriangleAlert,
	'tv': Tv,
	'type': Type,
	'user': User,
	'video': Video,
	'waves-horizontal': WavesHorizontal,
	'wifi': Wifi,
	'wind': Wind,
	'worm': Worm,
	'whole-word': WholeWord,
	'wrench': Wrench,
	'x': X,
	'zap': Zap,
};

